name: flutter_boilerplate
description: "Flutter Boilerplate"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # CORE PACKAGES
  intl: any
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  go_router: ^17.0.0
  shared_preferences: ^2.5.3
  json_annotation: ^4.9.0
  bloc: ^9.1.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/
